# Based partially on Alyxia's work, thanks so much!

name: Release
on:
  push:
    tags:
      - v*

env:
  FORCE_COLOR: true

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - id: go-cache-paths
        run: |
          echo "go_build=$(go env GOCACHE)" >> $GITHUB_ENV
          echo "go_mod=$(go env GOMODCACHE)" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: brew install pkg-config sdl2

      - name: Install Go dependencies
        run: go get -v

      - name: Build
        run: CGO_ENABLED=1 GOOS=darwin GOARCH=arm64 go build -v -tags static -ldflags "-s -w -X 'vencordinstaller/buildinfo.InstallerGitHash=$(git rev-parse --short HEAD)' -X 'vencordinstaller/buildinfo.InstallerTag=${{ github.ref_name }}'" -o VencordInstaller

      - name: Update executable
        run: |
          chmod +x VencordInstaller

      - name: Generate MacOS bundle
        run: |
          mkdir -p VencordInstaller.app/Contents/MacOS
          mkdir -p VencordInstaller.app/Contents/Resources
          cp macos/Info.plist VencordInstaller.app/Contents/Info.plist
          mv VencordInstaller VencordInstaller.app/Contents/MacOS/VencordInstaller
          cp macos/icon.icns VencordInstaller.app/Contents/Resources/icon.icns
          zip -r VencordInstaller.MacOS.zip VencordInstaller.app

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: VencordInstaller-macos
          path: VencordInstaller.MacOS.zip

  release:
    runs-on: ubuntu-latest
    needs: [build-mac]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: VencordInstaller-macos
          path: macos

      - name: Create the release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5 # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ github.ref_name }}
          prerelease: false
          draft: false
          files: |
            macos/VencordInstaller.MacOS.zip
